language: cpp
os:
    - linux
    - osx
    - windows
env:
    global:
        - OMP_NUM_THREADS=4
        - CFLAGS="-Wall -Wextra -pedantic -O3"
compiler:
    - g++
script:
    - "make clean && make && make tests && ./run_tests.sh"
