language: cpp
os:
    - linux
    - osx
env:
    global:
        - CFLAGS="-Wall -Wextra -pedantic -O3"
compiler:
    - g++
    - clang++
script:
    - "make clean && make && make tests && chmod a+x run_tests.sh && ./run_tests.sh"
